/**
 * Contant helpers
 * Always define the constants here in this file.
 *
 * Author: Vakadu Vinod
 */

export const CONSTANTS = {
	REGISTRATION_INFO: 'REGISTRATION_INFO',
	SORT_FILTER: 'SORT_FILTER',
	CATEGORY_FILTER: 'CATEGORY_FILTER',
	PAGE_SIZE: 24,
	UPI_SHEET: 'UPI',
	PPAY_SHEET: 'P_PAY',
	POD_SHEET: 'POD',
};

export const ORDER_CONSTANTS = {
	COD: 'cod',
	POD: 'POD',
	CUSTOMER_PARTIAL_PAY: 'CUSTOMER_PARTIAL_PAY',
	P_PAY: 'P_PAY',
	CUSTOMER_PREPAID: 'CUSTOMER_PREPAID',
	CASH_FREE: 'CASH_FREE',
	PREPAID_BY_UTR: 'PREPAID_BY_UTR',
	APPROVED: 'APPROVED',
	CONFIRMED: 'CONFIRMED',
	PICKED: 'PICKED',
	PACKED: 'PACKED',
	SHIPPED: 'SHIPPED',
	REJECTED: 'REJECTED',
	DELIVERED: 'DELIVERED',
	RETURN_REQUESTED: 'RETURN REQUESTED',
	RETURN_REJECTED: 'RETURN_REJECTED',
	RETURN_ACCEPTED: 'RETURN ACCEPTED',
	RETURNED: 'RETURNED',
	CANCELLED: 'CANCELLED',
	DELHIVERY: 'Third Party - Delhivery',
	SELLER_FOR_SELF: 'SELLER_FOR_SELF',
	ARZOOO_EXPRESS: 'ARZOOO_EXPRESS',
	OUT_FOR_DELIVERY_STATUS: 'OUT_FOR_DELIVERY',
	OUT_FOR_DELIVERY_LABEL: 'Out for delivery',
};

export const SORT_OPTIONS = [
	{ name: 'Price: Low to High', value: 'ASC' },
	{ name: 'Price: High to Low', value: 'DESC' },
];

export const POPULAR_BANKS = [
	{ value: '3021', name: 'HDFC' },
	{ value: '3022', name: 'ICICI' },
	{ value: '3044', name: 'SBI' },
	{ value: '3003', name: 'Axis' },
	{ value: '3032', name: 'Kotak' },
];

export const NETBANKING_LIST = [
	{ name: 'Allahabad Bank', value: '3001' },
	{ name: 'Allahabad Corporate', value: '3085' },
	{ name: 'Andhra Bank', value: '3002' },
	{ name: 'Andhra Bank Corporate', value: '3070' },
	{ name: 'Axis Bank Corporate', value: '3071' },
	{ name: 'Bank of Baroda - Corporate', value: '3060' },
	{ name: 'Bank of Baroda - Retail', value: '3005' },
	{ name: 'Bank of India', value: '3006' },
	{ name: 'Bank of India - Corporate', value: '3061' },
	{ name: 'Bank of Maharashtra', value: '3007' },
	{ name: 'Bandhan Bank- Corporate', value: '3079' },
	{ name: 'Barclays Corporate- Corporate', value: '3080' },
	{ name: 'Canara Bank', value: '3009' },
	{ name: 'Catholic Syrian Bank', value: '3010' },
	{ name: 'Central Bank of India', value: '3011' },
	{ name: 'City Union Bank', value: '3012' },
	{ name: 'City Union Bank of Corporate', value: '3083' },
	{ name: 'Corporation Bank', value: '3013' },
	{ name: 'DBS Bank Ltd', value: '3017' },
	{ name: 'DCB Bank - Corporate', value: '3062' },
	{ name: 'DCB Bank - Personal', value: '3018' },
	{ name: 'Deutsche Bank', value: '3016' },
	{ name: 'Dena Bank', value: '3015' },
	{ name: 'Dhanlakshmi Bank', value: '3019' },
	{ name: 'Dhanlakshmi Bank - Corporate', value: '3072' },
	{ name: 'Equitas Small Finance Bank', value: '3076' },
	{ name: 'Federal Bank', value: '3020' },
	{ name: 'HDFC Corporate', value: '3084' },
	{ name: 'ICICI Corporate Netbanking', value: '3073' },
	{ name: 'IDBI Bank', value: '3023' },
	{ name: 'Indian Bank', value: '3026' },
	{ name: 'IDFC Bank', value: '3024' },
	{ name: 'Indian Overseas Bank', value: '3027' },
	{ name: 'Indian Overseas Bank Corporate', value: '3081' },
	{ name: 'IndusInd Bank', value: '3028' },
	{ name: 'Jammu and Kashmir Bank', value: '3029' },
	{ name: 'Karnataka Bank Ltd', value: '3030' },
	{ name: 'Karur Vysya Bank', value: '3031' },
	{ name: 'Kotak Mahindra Bank', value: '3032' },
	{ name: 'Laxmi Vilas Bank - Retail', value: '3033' },
	{ name: 'Laxmi Vilas Bank - Corporate', value: '3064' },
	{ name: 'Oriental Bank of Commerce', value: '3035' },
	// { name: 'Punjab Sind Bank', value: '3037' },
	{ name: 'Punjab National Bank - Corporate', value: '3065' },
	{ name: 'Punjab National Bank - Retail', value: '3038' },
	{
		name: 'PNB (Erstwhile Oriental Bank of Commerce) - Corporate',
		value: '3082',
	},
	{ name: 'Ratnakar Corporate Banking', value: '3074' },
	{ name: 'RBL Bank', value: '3039' },
	{ name: 'Saraswat Bank', value: '3040' },
	{ name: 'Shamrao Vitthal Co-operative Bank', value: '3041' },
	{ name: 'Shamrao Vithal Bank Corporate', value: '3075' },
	{ name: 'South Indian Bank', value: '3042' },
	{ name: 'State Bank of India - Corporate', value: '3066' },
	{ name: 'Standard Chartered Bank', value: '3043' },
	{ name: 'Syndicate Bank', value: '3050' },
	{ name: 'Tamilnad Mercantile Bank Ltd', value: '3052' },
	{ name: 'Tamil Nadu State Co-operative Bank', value: '3051' },
	{ name: 'UCO Bank', value: '3054' },
	{ name: 'UBI (Erstwhile Corporation Bank) - Corporate', value: '3078' },
	{ name: 'Union Bank of India', value: '3055' },
	{ name: 'Union Bank of India - Corporate', value: '3067' },
	{ name: 'United Bank of India', value: '3056' },
	{ name: 'Vijaya Bank', value: '3057' },
	{ name: 'Yes Bank Ltd', value: '3058' },
	{ name: 'Yes Bank Corporate', value: '3077' },
];

export const MOP = {
	PREPAID: 'PREPAID',
	P_PAY: 'P_PAY',
	POD: 'POD',
	CREDIT: 'CREDIT',
};

export const PAY_THRU = {
	NET_BANKING: 'NET_BANKING',
	CREDIT_CARD: 'CREDIT_CARD',
	DEBIT_CARD: 'DEBIT_CARD',
	UPI: 'UPI',
	RUPIFI: 'RUPIFI',
	FINBOX: 'FINBOX',
	EPAYLATER: 'EPAYLATER',
	WALLET: 'WALLET',
	POD: 'POD',
	PREPAID: 'PREPAID',
	P_PAY: 'P_PAY',
	PAD: 'PAD',
	CREDIT: 'CREDIT',
	INDIFI: 'INDIFI',
	RTGS: 'RTGS/NEFT',
	BLACKSOIL: 'BLACKSOIL',
	OPEN_CREDIT: 'OPEN_CREDIT',
	GO_CARE_WALLET: 'GO_CARE_WALLET',
};
