const states = [
	{ state: ' Andaman And Nicobar Islands ', id: 1 },
	{ state: ' Andhra Pradesh ', id: 2 },
	{ state: ' Arunachal Pradesh ', id: 3 },
	{ state: ' Assam ', id: 4 },
	{ state: ' Bihar ', id: 5 },
	{ state: ' Chandigarh ', id: 6 },
	{ state: ' Chhattisgarh ', id: 7 },
	{ state: ' Dadra And Nagar Haveli ', id: 8 },
	{ state: ' Daman And Diu ', id: 37 },
	{ state: ' Delhi ', id: 9 },
	{ state: ' Goa ', id: 10 },
	{ state: ' Gujarat ', id: 11 },
	{ state: ' Haryana ', id: 12 },
	{ state: ' Himachal Pradesh ', id: 13 },
	{ state: ' Jammu And Kashmir ', id: 14 },
	{ state: ' Jharkhand ', id: 15 },
	{ state: ' Karnataka ', id: 16 },
	{ state: ' Kerala ', id: 17 },
	{ state: ' Ladakh ', id: 18 },
	{ state: ' Lakshadweep ', id: 19 },
	{ state: ' Madhya Pradesh ', id: 20 },
	{ state: ' Maharashtra ', id: 21 },
	{ state: ' Manipur ', id: 22 },
	{ state: ' Meghalaya ', id: 23 },
	{ state: ' Mizoram ', id: 24 },
	{ state: ' Nagaland ', id: 25 },
	{ state: ' Odisha ', id: 26 },
	{ state: ' Puducherry ', id: 27 },
	{ state: ' Punjab ', id: 28 },
	{ state: ' Rajasthan ', id: 29 },
	{ state: ' Sikkim ', id: 30 },
	{ state: ' Tamil Nadu ', id: 31 },
	{ state: ' Telangana ', id: 32 },
	{ state: ' Tripura ', id: 33 },
	{ state: ' Uttar Pradesh ', id: 34 },
	{ state: ' Uttarakhand ', id: 35 },
	{ state: ' West Bengal ', id: 36 },
];

const bankList = [
	{ name: 'Allahabad Bank', value: '3001' },
	{ name: 'Andhra Bank', value: '3002' },
	{ name: 'Axis Bank', value: '3003' },
	{ name: 'Bank of Baroda - Corporate', value: '3060' },
	{ name: 'Bank of Baroda - Retail', value: '3005' },
	{ name: 'Bank of India', value: '3006' },
	{ name: 'Bank of Maharashtra', value: '3007' },
	{ name: 'Canara Bank', value: '3009' },
	{ name: 'Catholic Syrian Bank', value: '3010' },
	{ name: 'Central Bank of India', value: '3011' },
	{ name: 'City Union Bank', value: '3012' },
	{ name: 'Corporation Bank', value: '3013' },
	{ name: 'DBS Bank Ltd', value: '3017' },
	{ name: 'DCB Bank - Corporate', value: '3062' },
	{ name: 'DCB Bank - Personal', value: '3018' },
	{ name: 'Deutsche Bank', value: '3016' },
	{ name: 'Dhanlakshmi Bank', value: '3019' },
	{ name: 'Federal Bank', value: '3020' },
	{ name: 'HDFC Bank', value: '3021' },
	{ name: 'ICICI Bank', value: '3022' },
	{ name: 'IDBI Bank', value: '3023' },
	{ name: 'Indian Bank', value: '3026' },
	{ name: 'Indian Overseas Bank', value: '3027' },
	{ name: 'IndusInd Bank', value: '3028' },
	{ name: 'Jammu and Kashmir Bank', value: '3029' },
	{ name: 'Karnataka Bank Ltd', value: '3030' },
	{ name: 'Karur Vysya Bank', value: '3031' },
	{ name: 'Kotak Mahindra Bank', value: '3032' },
	{ name: 'Laxmi Vilas Bank', value: '3033' },
	{ name: 'Oriental Bank of Commerce', value: '3035' },
	{ name: 'Punjab Sind Bank', value: '3037' },
	{ name: 'Punjab National Bank - Corporate', value: '3065' },
	{ name: 'Punjab National Bank - Retail', value: '3038' },
	{ name: 'Saraswat Bank', value: '3040' },
	{ name: 'South Indian Bank', value: '3042' },
	{ name: 'Standard Chartered Bank', value: '3043' },
	{ name: 'State Bank Of India', value: '3044' },
	{ name: 'Tamilnad Mercantile Bank Ltd', value: '3052' },
	{ name: 'UCO Bank', value: '3054' },
	{ name: 'Union Bank of India', value: '3055' },
	{ name: 'United Bank of India', value: '3056' },
	{ name: 'Vijaya Bank', value: '3057' },
	{ name: 'Yes Bank Ltd', value: '3058' },
];

export { states, bankList };
